### ISSUE TITLE
Form fields do not work on iPhone

### ISSUE THREAD

**Issue by imnlink** [filamentgroup/Overthrow#11]
I have a document containing form fields (input, textarea, radio/checkbox) that scrolls fine on Android, but on iPhone, the form fields do not work (when clicking them nothing happens). I am testing on a first generation iPhone with iOS version 3.1.3.
To replicate the issue, just add an input field to one of your examples and open the document on an iPhone (other versions that 3.1.3 might work fine, but I have no way right now to test a different version). Can someone confirm the issue and perhaps provide a solution? Thanks.

**Comment by Igor10k** [comment]
On Android 2.3 I had a textarea that worked only the first time I tapped it. Had to comment out all the mentions of `setPointers` to make it work right. Thanks for pointing at that.
