### ISSUE TITLE
dist directory is missing in the bower's package

### ISSUE THREAD

**Issue by sviatco** [filamentgroup/Overthrow#66]
In your bower.json file you specify the path to a directory, which does not exist yet:
"main": "dist/overthrow.js"

Apparently the intention is for us to build the distributed version of the overthrow ourselves by running the provided grunt:default task in the Gruntfile.

Could you please build your library before deploying the package to bower's repo?

Thanks.

**Comment by ddemid** [comment]
+1

**Comment by ZaDarkSide** [comment]
:+1:
