### ISSUE TITLE
`Uncaught TypeError: undefined is not a function ` occured in `overthrow-polyfill.js` line 23

### ISSUE THREAD

**Issue by leftstick** [filamentgroup/Overthrow#78]
Once i have `svg` element in the `document`, the error described in title was thrown without any fallback.

The reason is, the `target.className` returns `SVGAnimatedString` which does not provide an `indexOf` method, that's way the error happens.

The code as following:

``` javascript
// find closest overthrow (elem or a parent)
o.closest = function( target, ascend ){
    return !ascend && target.className && target.className.indexOf( scrollIndicatorClassName ) > -1 && target || o.closest( target.parentNode );
};
```

**Comment by ciromattia** [comment]
any news on this?
